// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4.Models;

namespace Mission4.Migrations
{
    [DbContext(typeof(MovieFormContext))]
    [Migration("20220127004055_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission4.Models.Movie_app_response", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Action/Sci-fi",
                            Director = "Peter Berg",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Battleship"
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Animated Musical Fantasy Comedy-Drama",
                            Director = "Aaron Blaise, Robert Walker",
                            Edited = false,
                            Rating = "G",
                            Title = "Brother Bear"
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Romance",
                            Director = "Lasse Stevens",
                            Edited = false,
                            Rating = "PG-13",
                            Title = "Safe Haven"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
